Prueba/Models/Productos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Id_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public string Categoria { get; set; }
        public int id_marca { get; set; }
    
        public virtual Marcas Marcas { get; set; }
    }
}

Prueba/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Prueba.Models;

namespace Prueba.Controllers
{
    public class MarcasController : Controller
    {
        private ConexionBD db = new ConexionBD();

//--------------------------------------------------------------Index Marcas--------------------------------------------------------------------------
        public ActionResult Index()
        {
            //Solicita la conexión con la bd y la tabla marcas para mostrarla en una lista
            return View(db.Marcas.ToList());
        }

//--------------------------------------------------------------Nueva marca--------------------------------------------------------------------------
        // GET
        public ActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken] // Asegura que la solicitud provenga de la misma aplicación.
        // El parámetro `marcas` es un objeto que contiene los datos del formulario. 
        public ActionResult Create([Bind(Include = "Id_Marca,Nombre_Marca,Representante")] Marcas marcas)
        {
            if (ModelState.IsValid) // Verifica si los datos son validos
            {
                db.Marcas.Add(marcas); // Agrega a la bd
                db.SaveChanges(); // Guarda los cambios hechos a la bd
                return RedirectToAction("Index"); // Redirige al index de la lista
            }

            // Si la validacion fallo, vuelve a mostrar el formulario
            return View(marcas);
        }

//--------------------------------------------------------------Edita marca--------------------------------------------------------------------------
        // GET
        public ActionResult Edit(int? id) // Recibe el parametro id
        {
            if (id == null) // Verifica si es nulo
            {
                // Si el id es nulo, devuelve un resultado de error HTTP 400 BadRequest, indicando que la solicitud es inválida.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Busca el id en la tabla de la bd
            Marcas marcas = db.Marcas.Find(id);
            if (marcas == null) // Verifica si hay resultados
            {
                // Si no se encuentra ese id, devuelve un resultado HTTP 404 NotFound
                return HttpNotFound();
            }
            // Si se encuentra el id, se envia a la vista para continuar
            return View(marcas);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken] // Asegura que la solicitud provenga de la misma aplicación.
        // El parámetro `marcas` es un objeto que contiene los datos del formulario. 
        public ActionResult Edit([Bind(Include = "Id_Marca,Nombre_Marca,Representante")] Marcas marcas)
        {
            if (ModelState.IsValid) // Verifica si los datos son validos
            {
                db.Entry(marcas).State = EntityState.Modified; // Realiza la actualización en la bd
                db.SaveChanges(); // Guarda los combios hechos
                return RedirectToAction("Index");  // Retorna al index
            }
            return View(marcas); // Si no son validos los datos, retorna a la vista
        }

//--------------------------------------------------------------Elimina marca--------------------------------------------------------------------------
        // GET
        public ActionResult Delete(int? id) // Recibe el parametro id
        {

            if (id == null) // Verifica si hay un id
            {
                // Si el id es nulo, devuelve un resultado de error HTTP 400 BadRequest, indicando que la solicitud es inválida.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Busca el id en la tabla de la bd
            Marcas marcas = db.Marcas.Find(id);
            if (marcas == null) // Verifica si encontro resultados
            {
                // Si no se encuentra ese id, devuelve un resultado HTTP 404 NotFound
                return HttpNotFound();
            }
            // Regresa a la vista para continuar con el proceso
            return View(marcas);
        }

        // POST
        // Este se ejecuta cuando se envia un formulario de eliminación
        [HttpPost, ActionName("Delete")] // Metodo post y alias del metodo delete
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // Busca el id en la bd
                Marcas marcas = db.Marcas.Find(id);
                if (marcas == null)
                {
                    return HttpNotFound();
                }

                // Verifica si la marca tiene productos relacionados
                if (marcas.Productos.Any())
                {
                    // Si hay productos relacionados, muestra un mensaje de error
                    ModelState.AddModelError("", "No se puede eliminar la marca porque tiene productos asociados.");
                    return View("Delete", marcas); // Retorna con un mensaje de error
                }

                // Si no hay productos asociados entonces elimina
                db.Marcas.Remove(marcas);
                db.SaveChanges();

                // Redirecciona al index
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Maneja cualquier otra excepción
                ModelState.AddModelError("", "Ocurrió un error al intentar eliminar la marca: " + ex.Message);
                return View("Delete", db.Marcas.Find(id)); // Retorna con un mensaje de error
            }
        }


//---------------------------------------------------------------------------------------------------------------------------------------------------
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Prueba/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Prueba.Models;

namespace Prueba.Controllers
{
    public class ProductosController : Controller
    {
        private ConexionBD db = new ConexionBD();

//--------------------------------------------------------------INDEX Y BUSQUEDA--------------------------------------------------------------------------
        // GET
        public ActionResult Index(string searchTerm) // Recibe el término de búsqueda del formulario
        {
            // Obtiene todos los productos e incluye la relación con las marcas
            var productos = db.Productos.Include(p => p.Marcas);

            // Verifica si existe un dato a buscar
            if (!string.IsNullOrEmpty(searchTerm))
            {
                // Filtra los productos que tengan como nombre o marca el dato
                productos = productos.Where(p => p.Nombre_Producto.Contains(searchTerm) || p.Marcas.Nombre_Marca.Contains(searchTerm));
            }

            // Convierte la consulta en lista y la envia a la vista
            return View(productos.ToList());
        }

//--------------------------------------------------------------REGISTRO--------------------------------------------------------------------------
        // GET
        public ActionResult Create()
        {
            //Crea una lista desplegable que usa el id como codigo y el nombre de la marca como opción de la lista
            ViewBag.id_marca = new SelectList(db.Marcas, "Id_Marca", "Nombre_Marca");
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Producto,Nombre_Producto,Categoria,id_marca")] Productos productos)
        {
            if (ModelState.IsValid) // Verifica que los datos sean validos
            {
                db.Productos.Add(productos); // Agvrega en la tabla 
                db.SaveChanges(); // Guarda los cambios de la bd
                return RedirectToAction("Index"); // Redirecciona al index
            }
            //En caso de no ser validos, retorna a la vista
            ViewBag.id_marca = new SelectList(db.Marcas, "Id_Marca", "Nombre_Marca", productos.id_marca);
            return View(productos);
        }

//--------------------------------------------------------------EDITAR--------------------------------------------------------------------------
        // GET
        public ActionResult Edit(int? id) // Recibe el id de l formulario
        {
            if (id == null) // Verifica que el id no sea nulo
            {
                // Si el id es nulo, devuelve un resultado de error HTTP 400 BadRequest, indicando que la solicitud es inválida.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Busca el id en la bd
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                // Si no se encuentra ese id, devuelve un resultado HTTP 404 NotFound
                return HttpNotFound();
            }
            ViewBag.id_marca = new SelectList(db.Marcas, "Id_Marca", "Nombre_Marca", productos.id_marca);
            return View(productos);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Producto,Nombre_Producto,Categoria,id_marca")] Productos productos) // Se ejecuta al confirmar la edición
        {
            if (ModelState.IsValid) // Verifica que los datos sean validos
            {
                db.Entry(productos).State = EntityState.Modified; // Realiza la actualizacián en la tabla
                db.SaveChanges(); // Guarda los cambios hechos
                return RedirectToAction("Index");
            }
            // Si los cambios no son validos, retorna a la vista
            ViewBag.id_marca = new SelectList(db.Marcas, "Id_Marca", "Nombre_Marca", productos.id_marca);
            return View(productos);
        }

//--------------------------------------------------------------ELIMINAR--------------------------------------------------------------------------
        // GET
        public ActionResult Delete(int? id) // Recibe el id del formulario 
        {
            if (id == null) // VErifica que el id no sea nulo
            {
                // Si el id es nulo, devuelve un resultado de error HTTP 400 BadRequest, indicando que la solicitud es inválida.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Busca el id en la tabla de la bd
            Productos productos = db.Productos.Find(id);
            if (productos == null) // Verifica que el id exista
            {
                // Si no se encuentra ese id, devuelve un resultado HTTP 404 NotFound
                return HttpNotFound();
            }
            return View(productos); 
        }

        // POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) // Se ejecuta el comfirmar la eliminación
        {
            Productos productos = db.Productos.Find(id); // Busca el id en la tabla de la bd
            db.Productos.Remove(productos); // Elimina el registro
            db.SaveChanges(); // Guarda los cambios hechos
            return RedirectToAction("Index"); // Redirecciona al index
        }


//--------------------------------------------------------------ELIMINACIÓN MULTIPLE--------------------------------------------------------------------------
        // POST 
        [HttpPost]
        // Al activarse el metodo, guarda todos los id seleccionados en un array
        public ActionResult EliminarSeleccionados(int[] productosSeleccionados)
        {
            if (productosSeleccionados != null && productosSeleccionados.Any()) // Verifica que existan datos en el array
            {
                foreach (var id in productosSeleccionados) // Recorre el array
                {
                    var producto = db.Productos.Find(id); // Busca el id seleccionado en la bd
                    if (producto != null) // Si existe, procede a eliminarlo
                    {
                        db.Productos.Remove(producto);
                    }
                }
                db.SaveChanges(); // Guarda los cambios en la bd
            }

            return RedirectToAction("Index"); // Redirecciona al index
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Prueba/Views/Productos/Create.cshtml
@model Prueba.Models.Productos

@{
    ViewBag.Title = "Registro de productos";
}

<h2>Registro de productos</h2>


@using (Html.BeginForm()) //Inicia formulario de html
{
    @Html.AntiForgeryToken() //Token de antifalsificación

    <!-- Contenedor de formulario horizontal -->
    <div class="form-horizontal">
        <hr />
        <!-- Muestra los errores de la validacion del formulario -->
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Nombre del producto :</label>
            <div class="col-md-10">
                <!-- Genera input -->
                @Html.EditorFor(model => model.Nombre_Producto, new { htmlAttributes = new { @class = "form-control" } })
                <!-- Muestra un mensaje de error si la validación falla -->
                @Html.ValidationMessageFor(model => model.Nombre_Producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Categoria :</label>
            <div class="col-md-10">
                <!-- Genera input -->
                @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })
                <!-- Muestra un mensaje de error si la validación falla -->
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Marca :</label>
            <div class="col-md-10">
                <!-- Genera un Drop Down Menu -->
                @Html.DropDownList("id_marca", null, htmlAttributes: new { @class = "form-control" })
                <!-- Muestra un mensaje de error si la validación falla -->
                @Html.ValidationMessageFor(model => model.id_marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prueba/Views/Productos/Delete.cshtml
@model Prueba.Models.Productos

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar producto</h2>

<h3>¿Estás seguro de esto?</h3>
<div>
    <h4>Productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre del producto :
        </dt>

        <dd>
            <!-- Nombre del producto -->
            @Html.DisplayFor(model => model.Nombre_Producto)
        </dd>

        <dt>
            Categoria :
        </dt>

        <dd>
            <!-- Categoria -->
            @Html.DisplayFor(model => model.Categoria)
        </dd>

        <dt>
            Marca :
        </dt>

        <dd>
            <!-- Marca -->
            @Html.DisplayFor(model => model.Marcas.Nombre_Marca)
        </dd>

    </dl>

    @using (Html.BeginForm()) { //Inicia formulario html
        @Html.AntiForgeryToken() //Token de antifalsificación

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Cancelar", "Index")
        </div>
    }
</div>

Prueba/Views/Productos/Edit.cshtml
@model Prueba.Models.Productos

@{
    ViewBag.Title = "Actualizar";
}

<h2>Actualizar</h2>


@using (Html.BeginForm()) //Inicia formulario de html
{
    @Html.AntiForgeryToken() //Token de antifalsificación

    <div class="form-horizontal">
        <hr />
        <!-- Muestra los errores de la validacion del formulario -->
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!-- Oculta el id de la marca traida -->
        @Html.HiddenFor(model => model.Id_Producto)

        <div class="form-group">
            <label class="control-label col-md-2">Nombre del producto :</label>
            <div class="col-md-10">
                <!-- Genera input -->
                @Html.EditorFor(model => model.Nombre_Producto, new { htmlAttributes = new { @class = "form-control" } })
                <!-- Muestra un mensaje de error si la validación falla -->
                @Html.ValidationMessageFor(model => model.Nombre_Producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Categoria :</label>
            <div class="col-md-10">
                <!-- Genera input -->
                @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })
                <!-- Muestra un mensaje de error si la validación falla -->
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Marca :</label>
            <div class="col-md-10">
                <!-- Genera un Drop Down Menu -->
                @Html.DropDownList("id_marca", null, htmlAttributes: new { @class = "form-control" })
                <!-- Muestra un mensaje de error si la validación falla -->
                @Html.ValidationMessageFor(model => model.id_marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prueba/Views/Productos/Index.cshtml
@model IEnumerable<Prueba.Models.Productos>

@{
    ViewBag.Title = "Productos";
}

<h2>Tabla de productos</h2>

<p>
    @Html.ActionLink("Ir a la tabla de marcas", "Index", "Marcas", null, new { @class = "btn btn-primary" })
</p>
<hr />
@using (Html.BeginForm("Index", "Productos", FormMethod.Get))
{
    <div class="form-group">
        <input type="text" name="searchTerm" placeholder="Buscar por nombre de producto o marca" class="form-control" value="@Request.QueryString["searchTerm"]" />
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
    </div>
}
<hr />

<!-- Crea formulario de eliminación multiple -->
@using (Html.BeginForm("EliminarSeleccionados", "Productos", FormMethod.Post))
{
    <div>
        <button type="submit" class="btn btn-danger">Eliminar seleccionados</button>
    </div>

    <table class="table">
            <tr>
                @Html.ActionLink("Ingresar nuevo producto", "Create", null, new { @class = "btn btn-link mr-3" })
            </tr>
            <hr />
            <tr>
                <th>
                    <!-- Columna de checkbox para seleccionar todos a la vez -->
                    <input type="checkbox" id="select-all" />
                </th>
                <th>Nombre del producto</th>
                <th>Categoria</th>
                <th>Marca</th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <!-- Checkbox para cada producto -->
                        <input type="checkbox" name="productosSeleccionados" value="@item.Id_Producto" />
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Nombre_Producto)</td>
                    <td>@Html.DisplayFor(modelItem => item.Categoria)</td>
                    <td>@Html.DisplayFor(modelItem => item.Marcas.Nombre_Marca)</td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = item.Id_Producto }) |
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.Id_Producto })
                    </td>
                </tr>
            }
    </table>
}

@section Scripts {
    <script>
        // Script para seleccionar o deseleccionar todos los checkboxes
        document.getElementById("select-all").addEventListener("click", function () {
            var checkboxes = document.getElementsByName("productosSeleccionados");
            for (var checkbox of checkboxes) {
                checkbox.checked = this.checked;
            }
        });
    </script>
}